### ISSUE TITLE
Deploy standard-contracts to live-libs?

### ISSUE THREAD

**Issue by redsquirrel** [androlo/standard-contracts#1]
@androlo I am developing an on-chain registry of reusable Solidity libraries via the https://github.com/consensys/live-libs project. Like your standard-contracts project, live-libs is still not ready for production, and I'd appreciate your feedback as a library author. If you're interested, take a look at it, and let me know if you deploy/register standard-contracts on morden/live-libs.

**Comment by androlo** [comment]
Hi. That is great. There really needs to be a list like that. I'll look into it more the coming week. Thanks.

**Comment by redsquirrel** [comment]
And libraries like yours really need to be shared more broadly! :)

**Comment by redsquirrel** [comment]
Update: I've implemented a way for library authors to receive ether in order to release their libs. 💰 

https://github.com/consensys/live-libs#funding-your-library

The "locking" is optional, but I figured it was a natural feature for a programming system with a built-in currency, which also requires authors to pay money (gas) to deploy their code.

**Comment by androlo** [comment]
Hi. Thanks for the update. I am looking at your site. This is not a "for profit" library though, but part of a push to create standard contracts for Solidity. It is also mostly just "internal libraries", i.e. the contracts wouldn't be deployed, but people would just import the code into the contracts they're making.

Since I am going over the material i will close the issue.
